void resetAll() {
        this.cRaw3.setVisibility(8);
        this.cRaw4.setVisibility(8);
        this.cRaw5.setVisibility(8);
        this.cRaw6.setVisibility(8);
        this.cRaw7.setVisibility(8);
        this.cRaw8.setVisibility(8);
        this.cRaw9.setVisibility(8);
        this.cRaw10.setVisibility(8);
        this.cRaw11.setVisibility(8);
        this.cRaw12.setVisibility(8);
        this.cCredit1ET.setText("");
        this.cCredit2ET.setText("");
        this.cCredit3ET.setText("");
        this.cCredit4ET.setText("");
        this.cCredit5ET.setText("");
        this.cCredit6ET.setText("");
        this.cCredit7ET.setText("");
        this.cCredit8ET.setText("");
        this.cCredit9ET.setText("");
        this.cCredit10ET.setText("");
        this.cCredit11ET.setText("");
        this.cCredit12ET.setText("");
        this.cSGPA_ET1.setText("");
        this.cSGPA_ET2.setText("");
        this.cSGPA_ET3.setText("");
        this.cSGPA_ET4.setText("");
        this.cSGPA_ET5.setText("");
        this.cSGPA_ET6.setText("");
        this.cSGPA_ET7.setText("");
        this.cSGPA_ET8.setText("");
        this.cSGPA_ET9.setText("");
        this.cSGPA_ET10.setText("");
        this.cSGPA_ET11.setText("");
        this.cSGPA_ET12.setText("");
        this.finish = false;
        this.permission1 = false;
        this.permission2 = false;
        this.permission3 = false;
        this.permission4 = false;
        this.permission5 = false;
        this.permission6 = false;
        this.permission7 = false;
        this.permission8 = false;
        this.permission9 = false;
        this.permission10 = false;
        this.permission11 = false;
        this.permission12 = false;
        this.addSemesterBtnClickCount = 2;
    }